---
title: "Final Project Proposal"
author: "Bin Lin"
date: "2016-11-17"
output: html_document
---

Introduction:

Since 2014, US has been spending more than $3 trillion dollars annually on healthcare and the average health expenditure is about $9523 per capita. In addition, these numbers keep increasing as those baby boomers start hitting their retirement age. If america spends too much resources on healthcare, there will be less money and resources we can spend on elsewhere because the budget is always limited. 


Objectives:

For this In final project, I want to create a markdown file that can show the breakdown of spending of medicare and medicaid. Some questions maybe addressed here. Here are the examples but not limited to

1. Are there certain states have higher than normal healthcare spending per capita?
2. What might be the potential reason behind that? (perform more procedures, take more expensive medications, more diseases that cost more money to treat ect)
3. If time permits and there are data available, I might also want to explore the influence of patient's education, immunization status, demographics on healthcare cost.



Data Resources:

So far I found some relevant datasets on this data.gov website. There are also data on CDC and CMS websites I can use. However, those data are not structured. I might consider enter them in SQL, or scrape the webpage or use its API.